version: '3.7'

name: node-docker

services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    tty: true
    entrypoint: sh -c "npm install && npm run start"
    volumes:
      - ./node:/usr/src/app
    networks:
      - node
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7.16
    container_name: mysql
    tty: true
    environment:
      - MYSQL_DATABASE=node
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - node
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node
    depends_on:
      - node
      
networks:
  node:
    driver: bridge